heading_control:
  omega: 0.75  # LF viser til 1.5
  zeta: 1.8   # LF viser til 1.0
  ki_scale: 5
  kp_scale: 15
  kd_scale: 2
  ki_saturation_limit: 15  #degrees
  N_rr: 25
  linearization_point: 0.2
  
speed_control:
  K_p: 0.3  # LF viser til 1
  kp_scale: 14
  ki_scale: 8
  ki_saturation_limit: 1.25  #m/s
  X_uu: 35

estimator:
  L1: 1
  omega_e: 0.2 # 0.65
  bias_gain: 0.2
  X_uu: 35
  Y_vv: 100
  N_rr: 100

waypoint:
  dp:
    delta: 5 # radius rundt wp i m
    tanh_var: 10
    max_nu: 2 # kts
  track:
    delta_max: 40 # avstanden fra p̃ til siktepunkt i m
    delta_tanh_var: 150
    nu_tanh_var: 10
    wp_radius: 5 # radius rundt wp i m
    LOS_dist: 50 # avstand fra wp i m hvor den går til line-of-sight
    LOS_toggle: False

debug:
  waypoint: 0
  estimator: False
  kontroller: False
  allokering: False