heading_control:
  omega: 0.5  # LF viser til 1.5
  zeta: 1.1   # LF viser til 1.0
  ki_scale: 5
  ki_saturation_limit: 15  #degrees
  N_rr: 25
  linearization_point: 0.2
  
speed_control:
  K_p: 0.8  # LF viser til 1
  ki_scale: 5
  ki_saturation_limit: 1.25  #m/s
  X_uu: 100

estimator:
  L1: 1
  omega_e: 0.65
  bias_gain: 1.0
  X_uu: 100
  Y_vv: 100
  N_rr: 100

waypoint:
  dp:
    delta: 5 # radius rundt wp i m
    tanh_var: 10
    max_nu: 2 # kts
  track:
    delta_max: 80 # avstanden fra p̃ til siktepunkt i m
    delta_tanh_var: 150
    LOS_dist: 50 # avstand fra wp i m hvor den går til line-of-sight
    nu_tanh_var: 10
    wp_radius: 3 # radius rundt wp i m