bool standby        # Alle kontrollfunksjoner er deaktivert
bool position       # Båten skal holde posisjon ved å sikte mot et fast punkt (en lat/lon) og holde en avstand på 5 meter
bool sail           # Båten fungerer som en vanlig autopilot, hvor kurs (eller heading) og fart settes manuelt gjennom HMI
bool track          # Båten skal følge en forhåndsdefinert bane basert på veipunkter fra en fil