ngc_sim:
  ros__parameters: # (data type) description
    #material and physichal parameters for "NTNU Arbeidsbaaten"
    roh: 1026.0      #(double) denstity of the water (kg/m³)

    #vehicle paramaters:
    m: 20000.0     #(double) total mass ofthe vehicle in kg
    payload: 0.0        #(double) payload
    r_g: [0.0,0.0,0.0]  #(double_array)location center of gravity (CG) relative to center of origin (CO) to the bodyfram {b} 
    l: 12.0              #(double) lengt
    b: 3.6              #(double) beam
    draft: 0.9          #(double) draft from water line

    #inertia dyadics coefficient needed to compute Ig
    R44: 1.4       #(double) radius of gyration in roll (~0.4 *B)
    R55: 3.0        #(double) radius of gyration in pitch(~0.25*L)
    R66: 3.0        #(double) radius of gyration in yaw (~0.25*L)

    #hydrostatic--> restoring coefficients/spring stifness - > resulting in the spring stiffnes matrix G
    A_wp: 2.0        #(double) waterplane area
    GMT: 0.0         #(double) transverse metacentric heights
    GML: 0.0         #(double) longtitudinal metacentric height
    LCF: 0.0         #(double) location of CF relative to CO
    r_p: 0.0         #(double) location of the pont CP relative to the CO
    
    
    #linear added mass terms derived by assuming the ship hull to be an elipsioid
    Xudot: 2030.0 #  aka. A11 = 2.7 *roh *nabla^(5/3) /L²  -- the approximation function of Snöding (1982)
    Yvdot: 16628.0    # 
    Yrdot: 20000.0    # 
    Zwdot: 16628.0    # 
    Kpdot: 8361.0     # 1.7* m *R66² (from Fossen vehicle sim)
    Mqdot: 83196.0    #
    Nrdot: 84833.0    # -pi(T/L)² *[1/12 + 0,017 CB * B/T - 0,33 (B/L)]      (eq. 4.12)
    
    #Linear damping terms
    Xu: 0.0         #(double) surge linear damping term 
    Xr: 1.0         #(double) damping element between surge and yaw
    Yv: 1.0         #(double) sway damping term
    Zw: 1.0         #(double) heave damping term
    Kp: 1.0         #(double) roll damping term
    Mq: 1.0         #(double) pitch damping term
    Nr: 1.0         #(double) yaw damping term
    Nu: 1.0         #(double) damping element between surge and yaw

    #Non-linear damping terms
    #second order (quadratic) damping terms
    



    #Nonlinear modeling considering the ship as a wing, Andrew Ross 2008: https://ntnuopen.ntnu.no/ntnu-xmlui/handle/11250/259440
    #XLD: eq. 4.76, p. 95
    Xuu: 130.0       #(double) surge second order damping term
    Xuuu: 0.0       #(double) surge cubic damping term
    #Xvv: 1.0
    Xurr: 1.0
    #Xrv: 1.0
    #Xuvv: 1.0
    #Xrvu: 1.0       #(double) 
    #Xurr: 1.0
    Nuur: 1.0
    Nur: 1.0
    
    #modeling the changes in lift and drag with respect to roll see. chap 4.4
    #dXLD: eq. 4.74, p.94
    Xvvphiphi: 0.0 #(double)
    Xvrphiphi: 0.0 #(double)
    Xrrphiphi: 0.0 #(double)  

    #YLD: eq. 4.31 p.85
    
    

    
    #dYLD: eq. 4.75, p.94
    Yuvphiphi: 0.0
    Yurphipi: 0.0
